type User = {
  userId: string;
  firstName: string;
  middleName: string;
  lastName: string;
  birthDate: string;
  gender: string;
  displayName: string;
  streetAddress: string;
  city: string;
  email: string;
  country: string;
  enabled: boolean;
  optedIntoMarketing: boolean;
  walletAddress: `0x${string}`;
  paperWalletAddress: `0x${string}`;
  paperRecoveryCode: string;
  musicGenre: string;
  hasClaimedGenesisCore: boolean;
  hasCompletedTutorial: boolean;
  avatarUrl: string;
  allowedInventoryTrackSlots?: number;
};

type ClaimAutogenerate = {
  canClaimAutogeneratedTrack: boolean;
};

interface LynxPostBody {
  user: LynxUser;
  history: LynxHistoryItem[];
}

interface LynxUser {
  unlockIds: string[];
  number_of_tracks_created?: number;
  number_of_stems_owned?: number;
}

interface LynxHistoryItem {
  role: 'user' | 'assistant' | 'function';
  content: ReactNode;
  hidden: boolean;
  name?: string;
  attachments?: LynxAttachment[];
}

interface LynxAttachment {
  url: string;
  type: 'audio/mp3';
  alt: string;
  payload: string;
}
