import useAuthenticatedQuery from '@/utils/hooks/api/useAuthenticatedQuery';
import { useCallback } from 'react';
import { elyxnirRequest } from '../../../request';

export const preload = () => void canClaimAutogenerate();

export const canClaimAutogenerate = async (): Promise<
  APIResponse<ClaimAutogenerate>
> => {
  const res = await elyxnirRequest(
    `user-profile/players/can-claim-autogenerated-track`,
    'GET'
  );

  const { status } = res;

  try {
    if (!res.ok) {
      console.error('Failed to fetch data');
      const { success, message } = await res.json();
      return { success, message, status };
    }

    const data = await res.json();

    return { success: true, data, status };
  } catch (e) {
    console.error(e);
    return { success: false, status };
  }
};

export function useCanClaimAutogenerate() {
  return useAuthenticatedQuery(useCallback(() => canClaimAutogenerate(), []));
}
