import { NextRequest } from 'next/server';
import { elyxnirRequest } from '../../../request';

export async function GET(request: NextRequest) {
  return elyxnirRequest({
    request,
    path: `user-profile/api/players/can-claim-autogenerated-track`,
  });
}
